sonar.projectKey=svitlanassp_infoseclabs
sonar.organization=svitlanassp
sonar.projectName=infoseclabs
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/*.spec
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=static/**, **/*.html, **/*.js, **/*.css
